[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = [
    "wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

# For fork testing
[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
